### ISSUE TITLE
Easy config yunohost install

### ISSUE THREAD

**Issue by tutle** [nextcloud/social#1186]
How to easy configure social app in nextcloud when it's in a subfolder (of a yunohost server) ?
I have the message ".well-known/webfinger" is not well configured but really don't know witch files or parameters to configure.
Thanks in advance for any help

**Comment by spaetz** [comment]
.well-known always needs to be in the root directory of your user's domain name. So if nextcloud has no chance of adding content to the root, there is no way to get social running (otherwise other fediverse server don't know where to reach you). So that depends on the configuration of your nginx frontend or whatever you use...

**Comment by artonge** [comment]
Closing as it does not seem related to Nextcloud but to Yunohost. Feel free to reopen if I am wrong.
