### ISSUE TITLE
Can't install on AIO 4.6.2 (NC 25.0.4): An error occurred during the request. Unable to proceed.

### ISSUE THREAD

**Issue by Moonbase59** [nextcloud/social#1703]
**Describe the bug**
Tried to install "Social" on AIO (NC 25.0.4) but it fails with above error. Upon closer inspection, it tries to download and install version 0.4.2 which is supposed to be for NC 21, according to the web page. It _should_ install 0.6.0-beta5 instead.

**To Reproduce**
1. Go to 'Apps'
2. Click on 'Social → Download and Enable'
3. Error shown at top right of screen.

**Expected behavior**
Offer the latest version to go with my instance, and install it.

**Screenshots**
—

**Client details:**
 - OS: Ubuntu 22.04 LTS server
 - Browser: Firefox 111.0
 - Device: Linux Mint 21.1 laptop

<details>
<summary>Server details</summary>

**Social app version:**

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
25.0.4

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by danielromney** [comment]
Same issue here.
Initial error seen in the UI:
An error occurred during the request. Unable to proceed.

Log
`<html>
<body>


Exception: Undefined constant Doctrine\DBAL\Types\Type::TEXT in file '/var/www/html/custom_apps/social/lib/Migration/Version0003Date20200611000001.php' line 228/var/www/html/lib/private/AppFramework/App.php - line 183:OC\AppFramework\Http\Dispatcher->dispatch([ "OCA\\Sett ... "], "enableApps")/var/www/html/lib/private/Route/Router.php - line 315:OC\AppFramework\App::main("OCA\\Settin ... r", "enableApps", [ "OC\\AppFr ... "], [ "settings. ... "])/var/www/html/lib/base.php - line 1055:OC\Route\Router->match("/settings/apps/enable")/var/www/html/index.php - line 36:OC::handleRequest()Caused by Error: Undefined constant Doctrine\DBAL\Types\Type::TEXT/var/www/html/custom_apps/social/lib/Migration/Version0003Date20200611000001.php - line 76:OCA\Social\Migration\Version0003Date20200611000001->createActors("*** sensiti ... *")/var/www/html/lib/private/DB/MigrationService.php - line 446:OCA\Social\Migration\Version0003Date20200611000001->changeSchema([ "OC\\Migra ... "], [ "Closure"], [ "oc_"])/var/www/html/lib/private/DB/MigrationService.php - line 409:OC\DB\MigrationService->migrateSchemaOnly("latest")/var/www/html/lib/private/Installer.php - line 153:OC\DB\MigrationService->migrate("latest", true)/var/www/html/apps/settings/lib/Controller/AppSettingsController.php - line 451:OC\Installer->installApp("social")/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 230:OCA\Settings\Controller\AppSettingsController->enableApps([ "social"], [])/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 137:OC\AppFramework\Http\Dispatcher->executeController([ "OCA\\Sett ... "], "enableApps")/var/www/html/lib/private/AppFramework/App.php - line 183:OC\AppFramework\Http\Dispatcher->dispatch([ "OCA\\Sett ... "], "enableApps")/var/www/html/lib/private/Route/Router.php - line 315:OC\AppFramework\App::main("OCA\\Settin ... r", "enableApps", [ "OC\\AppFr ... "], [ "settings. ... "])/var/www/html/lib/base.php - line 1055:OC\Route\Router->match("/settings/apps/enable")/var/www/html/index.php - line 36:OC::handleRequest()
--



</body>
</html>`

Server details
- OS: TrueNas Scale
- Device: Dell Poweredge R230, Intel Xeon, 32GB RAM

Deice Details
- Microsoft Surface with Windows 11
- Microsoft Edge Browser

**Comment by ArtificialOwl** [comment]
is it 0.4.x or 0.6.x that is installed this way ?

**Comment by srijansaxena11** [comment]
You need to change update channel to beta to get beta release version as updates. Since there is no stable update for the app after 0.4 for now therefore you are not getting any update.

![image](https://user-images.githubusercontent.com/34964694/232246877-c553e45c-1918-459a-92b9-8253053e8754.png)

You can close the issue after verifying.

**Comment by danielromney** [comment]
It did work updating to the beta channel. Now I am running into an issue with the "well-known" url stuff on my nextcloud instance. This isn't an issue with sisal so I will make this as solved.
Thank you for the response and solution.

**Comment by srijansaxena11** [comment]
> Now I am running into an issue with the "well-known" url stuff on my nextcloud instance.

Set your redirection rules for well-known error. https://help.nextcloud.com/t/netcloud-20-0-1-well-known-webfinger-and-well-known-nodeinfo-errors/113158

**Comment by srijansaxena11** [comment]
@Moonbase59 requesting you to close the issue.

**Comment by danielromney** [comment]
I appreciate the suggestion but none of these work in my case. I have my
nextcloud installed on TrueNas Scale and the nginx configuration file is
not where all the suggestions say it is.

**Comment by srijansaxena11** [comment]
It has to be somewhere. Let me know if you can setup Social app properly. I am facing few issues and would love to have some help in resolving them.

**Comment by Moonbase59** [comment]
Using AIO 4.8.1, how can I change to the Beta channel?
Is there a big risk of damaging anything working?

**Comment by Moonbase59** [comment]
So I did a backup and tried changing to the beta channel:

- `docker rm nextcloud-aio-mastercontainer`
- `sudo docker run --sig-proxy=false --name nextcloud-aio-mastercontainer --restart always --publish 80:80 --publish 8080:8080 --publish 8443:8443 --volume nextcloud_aio_mastercontainer:/mnt/docker-aio-config --volume /var/run/docker.sock:/var/run/docker.sock:ro nextcloud/all-in-one:beta`
- `sudo sysctl -w net.core.rmem_max=2500000` again (because it complained)
- Went to AIO web UI, which now shows AIO 4.9.0 instead of 4.8.1, updated and restarted containers
- Logged into my cloud instance, went to Apps and searched for "social", but it still only offers me version 0.4.2.

What is wrong?

**Comment by szaimen** [comment]
> What is wrong?

You should use this command to switch Nextcloud in AIO to the beta channel: `sudo docker exec --user www-data -it nextcloud-aio-nextcloud php occ config:system:set updater.release.channel --value=beta`

**Comment by szaimen** [comment]
However better would be something like `sudo docker exec --user www-data -it nextcloud-aio-nextcloud php occ  app:update social --allow-unstable`

**Comment by Moonbase59** [comment]
@szaimen Thanks for the help! I used the latter command and got Social 0.6.0-rc2 installed.

Upon following Nextcloud (the initial suggestion), it showed an error message like "unable to follow …" but actually now shows Nextcloud as being followed.

I’m now desperately looking for a means to follow others and can’t find any menu or docs on that. Say I wanted to follow **@matthias@blog.syvi.net** or **@tech-snippets@blog.syvi.net**, how would I do that?

**Comment by Moonbase59** [comment]
Ok, I think I found it: One has to use search. For some reason this didn’t work with my _writefreely_ accounts shown above but it works with other instances like **@AzuraCast@fosstodon.org**.

**Comment by srijansaxena11** [comment]
@Moonbase59 can you close the issue now

**Comment by Moonbase59** [comment]
Yep, thanks for the reminder. I still wonder why following writefreely instances doesn’t work, but that’s another issue.
