### ISSUE TITLE
Support for Nextcloud 29 & 30

### ISSUE THREAD

**Issue by NatoBoram** [nextcloud/social#1889]
A tracking issue for people who want to be notified when this will be updated.

**Comment by GVLLIFESTYLE** [comment]
I need that as well.
I have social configured at NC 30 and it simply does not work.
When I click on profile it spins like forever and I cannot find my instance at any fediverse platform.
My nextcloud runs under https://www.mydomain.com/nextcloud

**Comment by paulvt** [comment]
The not being able to view profiles is already filed as #1883 and an issue since NC 28.

**Comment by GVLLIFESTYLE** [comment]
Still another issue:
I cannot find my instance at any fediverse platform at all.
And I cannot really interact with other fediverse platforms from social without any issues.
Maybe its related to the fact that my nextcloud is under /nextcloud/...

**Comment by GVLLIFESTYLE** [comment]
Is this planed, for when?

**Comment by JimmyKater** [comment]
referring to the app-page on apps.nextcloud.com there's a version (0.7.0) available fpr NC 29 and NC30.
look here: https://apps.nextcloud.com/apps/social/releases?platform=30#30

And yes, you can install it. But at least with my server (NC 29.0.8./AIO) it throws the wellknown "webfinger misconf"-error

**Comment by paulvt** [comment]
> referring to the app-page on apps.nextcloud.com there's a version (0.7.0) available fpr NC 29 and NC30. look here: https://apps.nextcloud.com/apps/social/releases?platform=30#30
> 
> And yes, you can install it. But at least with my server (NC 29.0.8./AIO) it throws the wellknown "webfinger misconf"-error

This is issue [#1888](https://github.com/nextcloud/social/issues/1888).
I also have the error, but I do get new messages for the people/organisations I follow. So it is somewhat functional.
The "cannot show profile" issue is also still there (see issue [#1883](https://github.com/nextcloud/social/issues/1883)).

**Comment by JimmyKater** [comment]
@paulvt I know.

but I think 'there's a version (0.7.0) available for NC 29 and NC30.'
would solve this thread, though

**Comment by noci2012** [comment]
It is available, but still fails to work as advertised.
(it is choking on missing database tables).

**Comment by joshtrichards** [comment]
Fixed in 20d668e (released as 0.7.0 for v29 and v30).

The other matters are covered elsewhere.

The `Exception parse_str(): Argument #1 ($string) must be of type string, null given in file '/opt/nextcloud/apps/social/lib/WellKnown/WebfingerHandler.php` matter is covered in #1888. Commented further on that matter there.

The webfinger is misconfigured matter is a mixture of `social` not handling missing required parameters correctly (basically #1888) and the an interaction with the setup checks in `server` which are designed for a stock install w/o `social` (based on a cursory look; will need a closer look to be certain).

@noci2012 Your db error is unrelated to any of this. That table has existed since 2022 so no idea why you don't have it. No one else has reported a similar problem. Wild guess: you had some of those old `social_3` tables (see #1871) and maybe accidentally dropped the real tables? May want to post on the help forum: https://help.nextcloud.com about that.

**Comment by noci2012** [comment]
wrt. db tables...

I installed a fresh NEW nextcloud, without tables & social installed social... then there are still no tables.
none at all. neither old nor new ones.

BEFORE attempting to install remove all items in the db table that tracks what is installed.
Appearantly there is a defect in the cleanup of applications that it doesn't clean the history of old upgrades (went back to NC 18 in this case for others even older)  when removing an application. 
==> no upgrades on tables etc.

After this  Social still doesn't work... at least the tables got created.
