### ISSUE TITLE
Timeline should display images from Mastodon posts

### ISSUE THREAD

**Issue by gerco** [nextcloud/social#230]
**Describe the bug**
Nextcloud Social does not display images in posts from followed accounts

**To Reproduce**
1. Go to Social
2. Follow a Mastodon user that posts images
3. Wait until they post a new image
4. Observe that only the text is displayed in the timeline on Nextcloud, no image is visible.

**Expected behavior**
The posted image(s) should be visible, content warnings should also be respected if possible.

**Client details:**
 - OS: Mac OS 10.14.2
 - Browser Chrome
 - Version 70
 - Device: Macbook Pro

<details>
<summary>Server details</summary>
**Social app version:**
0.1.0

**Operating system**:
Ubuntu Linux 18.04.1

**Web server:**
Apache 2

**Database:**
Postgresql 10

**PHP version:**
7.2.7-0ubuntu0.18.04.2

**Nextcloud version:** (see Nextcloud admin page)
15.0.0
</details>

**Comment by jancborchardt** [comment]
Yes, there is no image support at all yet. Also see **Adding images to posts #106**

**Comment by StCyr** [comment]
Hello,

The first thing is to get the back-end to provide the front-end with the url of the images to display.

I've investigated the matter and have a question:

In StreamRequest.php, all getTimeline* functions call parseStreamSelectSql to create an array of objects from the data fetched from the DB.

This parseStreamSelectSql function creates an object of type 'Stream' and initalize its properties from the data fetched from the DB:

```
        protected function parseStreamSelectSql(array $data, string $as = Stream::TYPE): Stream {
                /** @var Stream $item */
                $item = AP::$activityPub->getItemFromType($as);
                $item->importFromDatabase($data);
```

But, the 'Stream' object doesn't import attachments, only the 'Notes' does.

As a result, the objects in the array returned from the various getTimeline* functions don't contain any attachment property, and the front-end as nothing to display images.

I don't know anything about ActivityPub, so I'm asking: 

Couldn't we change the call to parseStreamSelectSql in the various getTimeline* functions to create 'Note' objects rather than 'Stream'? 

Cyrille

**Comment by StCyr** [comment]
Indeed, front-end gets the attachment when parserStreamSelectSql is called with $as = Note::TYPE:

```
        public function getTimelineHome(Person $actor, int $since = 0, int $limit = 5): array {
                $qb = $this->getStreamSelectSql();

                $this->leftJoinFollowing($qb, $actor);
                $this->limitToFollowing($qb, $actor);
                $this->limitPaginate($qb, $since, $limit);

                $this->leftJoinCacheActors($qb, 'object_id', $actor, 'f');
                $this->leftJoinStreamAction($qb);

                $this->filterDuplicate($qb);

                $streams = [];
                $cursor = $qb->execute();
                while ($data = $cursor->fetch()) {
                        try {
---                                $streams[] = $this->parseStreamSelectSql($data);
+++                                $streams[] = $this->parseStreamSelectSql($data, Note::TYPE);
                        } catch (Exception $e) {
                        }
                }
                $cursor->closeCursor();

                return $streams;
        }
```

![Capture d’écran 2019-07-11 à 15 09 33](https://user-images.githubusercontent.com/8179031/61053791-862ab300-a3ee-11e9-9f0f-6c7a4be328ed.png)

Can someone a bit knowledgeable assess this proposal?

**Comment by daita** [comment]
yup, 

> Couldn't we change the call to parseStreamSelectSql in the various getTimeline* functions to create 'Note' objects rather than 'Stream'?

No. But I can fix it so that attachments are imported when available

**Comment by daita** [comment]
#624 should fix the issue of attachments within the stream
