### ISSUE TITLE
Undraw images are not under a MIT license

### ISSUE THREAD

**Issue by maiki** [nextcloud/social#277]
There are 8 included images from the undraw project. Unfortunately, that project is no longer licensed under the MIT license, it was changed sometime in the last year:

* https://web.archive.org/web/20180103010308/https://undraw.co/license
* https://web.archive.org/web/20181208102541/https://undraw.co/license

My recommendation is to remove the images and reference to the collection. I don't know where they are used (my NC isn't updated to use the app yet), but I'm sure we can crowdsource a search for alternatives.

**Comment by jancborchardt** [comment]
The unDraw license is:

> You can use the illustrations published on unDraw for personal and commercial projects, without the need to include attribution.

So basically CC0, but with this addition:

> This license does not include the right to compile assets, vectors or images from unDraw to replicate a similar or competing service, in any form. This extends to automated ways to scrape, search or download the assets included on the website without our consent.

Which is kind of the same that Unsplash and Pexels are doing. It’s unfortunate they go this way instead of plain Creative Commons Attribution (- ShareAlike) or CC0, but it doesn’t make it unusable for us, no? cc @schiessle for further licensing questions.

Also, @Ninalimpi of unDraw is aware that we use her illustrations and positive about it: https://twitter.com/jancborchardt/status/1075797407013724160 :slightly_smiling_face:
Either that could already be seen as a license or we could her if it’s ok to use the images we need under CC-BY for example (as we already attribute anyway even though it’s not asked).

**Comment by daita** [comment]
@jancborchardt  can we close this ?

**Comment by Ninalimpi** [comment]
Guys you can close this... There is no need to attribute me or unDraw and you are only using 8 images which is cool and no need to discuss it further. The problem and main reason we switched from MIT was that people were ripping unDraw constantly, skyrocketing the CDN costs that we pay ourselves, without any purpose, other than promoting themselves. Btw, thank you for the attribution so far!

**Comment by jancborchardt** [comment]
@Ninalimpi thanks for the clarification! :) And thanks a lot for the illustrations in the first place. We will of course continue to attribute.

**Comment by Ninalimpi** [comment]
And I'll continue to appreciate it!!! Thank you and sorry for the whole mess with the license, once more!
