### ISSUE TITLE
three-dot-menu overlay

### ISSUE THREAD

**Issue by daita** [nextcloud/social#434]
@violoncelloCH reported this during the dev: https://github.com/nextcloud/social/pull/323#pullrequestreview-206276749

when the three-dot-menu is opened and you hover it again, a "more actions" popover is shown over the open menu, what doesn't really make sense... I think this should not be shown if the menu is already open...

**Comment by violoncelloCH** [comment]
why have you closed this? is it solved?

**Comment by daita** [comment]
my bad :]

**Comment by StCyr** [comment]
so, it's not that easy eventualy :-)

The thing is, nextcloud uses https://github.com/Akryum/v-tooltip for its tooltip framework. And, it doesn't seem to be designed to work with a popover menu.

So, the solution will probably be some kind of hack... :-(

IMHO, better solutions could be:

1. Removing the tooltip altogether;
2. Remove the popover menu and put its content in the tooltip directly;
3. Use https://vuetifyjs.com/en/components/tooltips instead of the one provided by nextcloud-vue  (it provides a `disabled` attribute which might be a solution to this issue);
4. Have nextcloud use https://vuetifyjs.com/en/components/tooltips for its tooltip framework.

If none of these solutions fit you, the following options provided by the nextcloud framework might be considered:

1. `trigger` - Events triggering the tooltip separated with spaces: 'hover', 'click', 'focus' or 'manual' ('manual' can't be combined with any other event).
2. `show` - Boolean to manually open or hide the tooltip.
3. `autoHide` - Boolean: automatically close the tooltip on mouseover.
4. `hideOnTargetClick` - Boolean: automatically close the tooltip on target click.

Finaly, one last solution might be to add/remove the "has-tooltip" class in the `togglePopoverMenu` and `hidePopoverMenu` functions of the `popoverMenu` mixin.

'Just thinking out loud here....

Br,

Cyrille

**Comment by daita** [comment]
@skjnldsv @juliushaertl @violoncelloCH what do you think ? do you have already encountered the same issue with Akryum/v-tooltip in some other place ?

**Comment by skjnldsv** [comment]
I really don't get the issue can we have screenshots? :)

**Comment by daita** [comment]
![](https://giant.gfycat.com/AlarmedAngelicChanticleer.gif)

**Comment by skjnldsv** [comment]
Okay, I see you're not using the Actions menu.
It should be fixed once you migrate to this :)

Or you can just use the open variable to make sure not to give a string to the v-tooltip directive like `v-tooltip.bottom="open ? '' : t('social', 'More actions')"`

**Comment by StCyr** [comment]
Cool!

Thanks, I’ll try that :-)
